---
title: The Bowen Street Book Club
timezone: UTC
collections:
  books:
    title: Books
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: books
  values:
    author: ''
    image: ''
email: jakecooperdesign@gmail.com
description: No meetings. No dues. Just One book at a time. A little bit each week,
  with recaps and insights in your inbox.
baseurl: ''
url: http://bowenstreetbookclub.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
