---
title: The Bowen Street Book Club
timezone: UTC
collections:
  books:
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jakecooperdesign@gmail.com
description: No meetings. No dues. Just One book at a time. A little bit each week, with recaps and insights in your inbox.
baseurl: ''
url: "http://bowenstreetbookclub.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
defaults:
  - 
    scope: 
      path: "books"
    values: 
      author: ""
      image: ""
